export const countriesData = [
  {
    "country": "Afghanistan",
    "flag": "🇦🇫",
    "iso2": "AF",
    "iso3": "AFG",
    "capital": "Kabul",
    "region": "Asia",
    "subregion": "Southern Asia",
    "population": 40099462,
    "area": 652864,
    "languages": ["Pashto", "Uzbek", "Turkmen"],
    "phoneCode": "+93",
    "timezones": ["Asia/Kabul"],
    "currency": {
      "name": "Afghan afghani",
      "code": "AFN",
      "symbol": "؋"
    },
    "tld": ".af",
    "latitude": 33.0,
    "longitude": 65.0
  },
  {
    "country": "Albania",
    "flag": "🇦🇱",
    "iso2": "AL",
    "iso3": "ALB",
    "capital": "Tirana",
    "region": "Europe",
    "subregion": "Southern Europe",
    "population": 2854710,
    "area": 28748,
    "languages": ["Albanian"],
    "phoneCode": "+355",
    "timezones": ["Europe/Tirane"],
    "currency": {
      "name": "Albanian lek",
      "code": "ALL",
      "symbol": "L"
    },
    "tld": ".al",
    "latitude": 41.0,
    "longitude": 20.0
  },
  {
    "country": "Algeria",
    "flag": "🇩🇿",
    "iso2": "DZ",
    "iso3": "DZA",
    "capital": "Algiers",
    "region": "Africa",
    "subregion": "Northern Africa",
    "population": 43053054,
    "area": 2381741,
    "languages": ["Arabic", "Tamazight"],
    "phoneCode": "+213",
    "timezones": ["Africa/Algiers"],
    "currency": {
      "name": "Algerian dinar",
      "code": "DZD",
      "symbol": "د.ج"
    },
    "tld": ".dz",
    "latitude": 28.0,
    "longitude": 3.0
  },
  {
    "country": "Andorra",
    "flag": "🇦🇩",
    "iso2": "AD",
    "iso3": "AND",
    "capital": "Andorra la Vella",
    "region": "Europe",
    "subregion": "Southern Europe",
    "population": 77142,
    "area": 468,
    "languages": ["Catalan"],
    "phoneCode": "+376",
    "timezones": ["Europe/Andorra"],
    "currency": {
      "name": "Euro",
      "code": "EUR",
      "symbol": "€"
    },
    "tld": ".ad",
    "latitude": 42.5,
    "longitude": 1.5
  },
  {
    "country": "Angola",
    "flag": "🇦🇴",
    "iso2": "AO",
    "iso3": "AGO",
    "capital": "Luanda",
    "region": "Africa",
    "subregion": "Middle Africa",
    "population": 31825295,
    "area": 1246700,
    "languages": ["Portuguese"],
    "phoneCode": "+244",
    "timezones": ["Africa/Luanda"],
    "currency": {
      "name": "Angolan kwanza",
      "code": "AOA",
      "symbol": "Kz"
    },
    "tld": ".ao",
    "latitude": -12.5,
    "longitude": 18.5
  },
  {
    "country": "Argentina",
    "flag": "🇦🇷",
    "iso2": "AR",
    "iso3": "ARG",
    "capital": "Buenos Aires",
    "region": "Americas",
    "subregion": "South America",
    "population": 45376763,
    "area": 2780400,
    "languages": ["Spanish", "Guaraní"],
    "phoneCode": "+54",
    "timezones": ["America/Argentina/Buenos_Aires", "America/Argentina/Cordoba", "America/Argentina/Salta"],
    "currency": {
      "name": "Argentine peso",
      "code": "ARS",
      "symbol": "$"
    },
    "tld": ".ar",
    "latitude": -34.0,
    "longitude": -64.0
  },
  {
    "country": "Armenia",
    "flag": "🇦🇲",
    "iso2": "AM",
    "iso3": "ARM",
    "capital": "Yerevan",
    "region": "Asia",
    "subregion": "Western Asia",
    "population": 2963243,
    "area": 29743,
    "languages": ["Armenian"],
    "phoneCode": "+374",
    "timezones": ["Asia/Yerevan"],
    "currency": {
      "name": "Armenian dram",
      "code": "AMD",
      "symbol": "֏"
    },
    "tld": ".am",
    "latitude": 40.0,
    "longitude": 45.0
  },
  {
    "country": "Australia",
    "flag": "🇦🇺",
    "iso2": "AU",
    "iso3": "AUS",
    "capital": "Canberra",
    "region": "Oceania",
    "subregion": "Australia and New Zealand",
    "population": 25687041,
    "area": 7692024,
    "languages": ["English"],
    "phoneCode": "+61",
    "timezones": ["Australia/Lord_Howe", "Australia/Hobart", "Australia/Currie", "Australia/Melbourne", "Australia/Sydney", "Australia/Broken_Hill", "Australia/Brisbane", "Australia/Lindeman", "Australia/Adelaide", "Australia/Darwin", "Australia/Perth", "Australia/Eucla"],
    "currency": {
      "name": "Australian dollar",
      "code": "AUD",
      "symbol": "$"
    },
    "tld": ".au",
    "latitude": -27.0,
    "longitude": 133.0
  },
  {
    "country": "Austria",
    "flag": "🇦🇹",
    "iso2": "AT",
    "iso3": "AUT",
    "capital": "Vienna",
    "region": "Europe",
    "subregion": "Western Europe",
    "population": 8917205,
    "area": 83871,
    "languages": ["German"],
    "phoneCode": "+43",
    "timezones": ["Europe/Vienna"],
    "currency": {
      "name": "Euro",
      "code": "EUR",
      "symbol": "€"
    },
    "tld": ".at",
    "latitude": 47.33,
    "longitude": 13.33
  },
  {
    "country": "Azerbaijan",
    "flag": "🇦🇿",
    "iso2": "AZ",
    "iso3": "AZE",
    "capital": "Baku",
    "region": "Asia",
    "subregion": "Western Asia",
    "population": 10110116,
    "area": 86600,
    "languages": ["Azerbaijani"],
    "phoneCode": "+994",
    "timezones": ["Asia/Baku"],
    "currency": {
      "name": "Azerbaijani manat",
      "code": "AZN",
      "symbol": "₼"
    },
    "tld": ".az",
    "latitude": 40.5,
    "longitude": 47.5
  },
  {
    "country": "Bahrain",
    "flag": "🇧🇭",
    "iso2": "BH",
    "iso3": "BHR",
    "capital": "Manama",
    "region": "Asia",
    "subregion": "Western Asia",
    "population": 1701583,
    "area": 765,
    "languages": ["Arabic"],
    "phoneCode": "+973",
    "timezones": ["Asia/Bahrain"],
    "currency": {
      "name": "Bahraini dinar",
      "code": "BHD",
      "symbol": ".د.ب"
    },
    "tld": ".bh",
    "latitude": 26.0,
    "longitude": 50.55
  },
  {
    "country": "Bangladesh",
    "flag": "🇧🇩",
    "iso2": "BD",
    "iso3": "BGD",
    "capital": "Dhaka",
    "region": "Asia",
    "subregion": "Southern Asia",
    "population": 164689383,
    "area": 147570,
    "languages": ["Bengali"],
    "phoneCode": "+880",
    "timezones": ["Asia/Dhaka"],
    "currency": {
      "name": "Bangladeshi taka",
      "code": "BDT",
      "symbol": "৳"
    },
    "tld": ".bd",
    "latitude": 24.0,
    "longitude": 90.0
  },
  {
    "country": "Belgium",
    "flag": "🇧🇪",
    "iso2": "BE",
    "iso3": "BEL",
    "capital": "Brussels",
    "region": "Europe",
    "subregion": "Western Europe",
    "population": 11555997,
    "area": 30528,
    "languages": ["Dutch", "French", "German"],
    "phoneCode": "+32",
    "timezones": ["Europe/Brussels"],
    "currency": {
      "name": "Euro",
      "code": "EUR",
      "symbol": "€"
    },
    "tld": ".be",
    "latitude": 50.83,
    "longitude": 4.0
  },
  {
    "country": "Brazil",
    "flag": "🇧🇷",
    "iso2": "BR",
    "iso3": "BRA",
    "capital": "Brasília",
    "region": "Americas",
    "subregion": "South America",
    "population": 212559409,
    "area": 8515767,
    "languages": ["Portuguese"],
    "phoneCode": "+55",
    "timezones": ["America/Noronha", "America/Belem", "America/Fortaleza", "America/Recife", "America/Araguaina", "America/Maceio", "America/Bahia", "America/Sao_Paulo", "America/Campo_Grande", "America/Cuiaba", "America/Santarem", "America/Porto_Velho", "America/Boa_Vista", "America/Manaus", "America/Eirunepe", "America/Rio_Branco"],
    "currency": {
      "name": "Brazilian real",
      "code": "BRL",
      "symbol": "R$"
    },
    "tld": ".br",
    "latitude": -10.0,
    "longitude": -55.0
  },
  {
    "country": "Canada",
    "flag": "🇨🇦",
    "iso2": "CA",
    "iso3": "CAN",
    "capital": "Ottawa",
    "region": "Americas",
    "subregion": "Northern America",
    "population": 38005238,
    "area": 9984670,
    "languages": ["English", "French"],
    "phoneCode": "+1",
    "timezones": ["America/St_Johns", "America/Halifax", "America/Glace_Bay", "America/Moncton", "America/Goose_Bay", "America/Blanc-Sablon", "America/Toronto", "America/Nipigon", "America/Thunder_Bay", "America/Iqaluit", "America/Pangnirtung", "America/Resolute", "America/Atikokan", "America/Rankin_Inlet", "America/Winnipeg", "America/Rainy_River", "America/Regina", "America/Swift_Current", "America/Edmonton", "America/Cambridge_Bay", "America/Yellowknife", "America/Inuvik", "America/Creston", "America/Dawson_Creek", "America/Fort_Nelson", "America/Vancouver", "America/Whitehorse", "America/Dawson"],
    "currency": {
      "name": "Canadian dollar",
      "code": "CAD",
      "symbol": "$"
    },
    "tld": ".ca",
    "latitude": 60.0,
    "longitude": -95.0
  },
  {
    "country": "China",
    "flag": "🇨🇳",
    "iso2": "CN",
    "iso3": "CHN",
    "capital": "Beijing",
    "region": "Asia",
    "subregion": "Eastern Asia",
    "population": 1402112000,
    "area": 9640011,
    "languages": ["Chinese"],
    "phoneCode": "+86",
    "timezones": ["Asia/Shanghai", "Asia/Urumqi"],
    "currency": {
      "name": "Chinese yuan",
      "code": "CNY",
      "symbol": "¥"
    },
    "tld": ".cn",
    "latitude": 35.0,
    "longitude": 105.0
  },
  {
    "country": "Colombia",
    "flag": "🇨🇴",
    "iso2": "CO",
    "iso3": "COL",
    "capital": "Bogotá",
    "region": "Americas",
    "subregion": "South America",
    "population": 50882884,
    "area": 1141748,
    "languages": ["Spanish"],
    "phoneCode": "+57",
    "timezones": ["America/Bogota"],
    "currency": {
      "name": "Colombian peso",
      "code": "COP",
      "symbol": "$"
    },
    "tld": ".co",
    "latitude": 4.0,
    "longitude": -72.0
  },
  {
    "country": "Denmark",
    "flag": "🇩🇰",
    "iso2": "DK",
    "iso3": "DNK",
    "capital": "Copenhagen",
    "region": "Europe",
    "subregion": "Northern Europe",
    "population": 5831404,
    "area": 43094,
    "languages": ["Danish"],
    "phoneCode": "+45",
    "timezones": ["Europe/Copenhagen"],
    "currency": {
      "name": "Danish krone",
      "code": "DKK",
      "symbol": "kr"
    },
    "tld": ".dk",
    "latitude": 56.0,
    "longitude": 10.0
  },
  {
    "country": "Egypt",
    "flag": "🇪🇬",
    "iso2": "EG",
    "iso3": "EGY",
    "capital": "Cairo",
    "region": "Africa",
    "subregion": "Northern Africa",
    "population": 102334403,
    "area": 1002450,
    "languages": ["Arabic"],
    "phoneCode": "+20",
    "timezones": ["Africa/Cairo"],
    "currency": {
      "name": "Egyptian pound",
      "code": "EGP",
      "symbol": "£"
    },
    "tld": ".eg",
    "latitude": 27.0,
    "longitude": 30.0
  },
  {
    "country": "Finland",
    "flag": "🇫🇮",
    "iso2": "FI",
    "iso3": "FIN",
    "capital": "Helsinki",
    "region": "Europe",
    "subregion": "Northern Europe",
    "population": 5530719,
    "area": 338424,
    "languages": ["Finnish", "Swedish"],
    "phoneCode": "+358",
    "timezones": ["Europe/Helsinki"],
    "currency": {
      "name": "Euro",
      "code": "EUR",
      "symbol": "€"
    },
    "tld": ".fi",
    "latitude": 64.0,
    "longitude": 26.0
  },
  {
    "country": "France",
    "flag": "🇫🇷",
    "iso2": "FR",
    "iso3": "FRA",
    "capital": "Paris",
    "region": "Europe",
    "subregion": "Western Europe",
    "population": 67391582,
    "area": 551695,
    "languages": ["French"],
    "phoneCode": "+33",
    "timezones": ["Europe/Paris"],
    "currency": {
      "name": "Euro",
      "code": "EUR",
      "symbol": "€"
    },
    "tld": ".fr",
    "latitude": 46.0,
    "longitude": 2.0
  },
  {
    "country": "Germany",
    "flag": "🇩🇪",
    "iso2": "DE",
    "iso3": "DEU",
    "capital": "Berlin",
    "region": "Europe",
    "subregion": "Western Europe",
    "population": 83240525,
    "area": 357114,
    "languages": ["German"],
    "phoneCode": "+49",
    "timezones": ["Europe/Berlin"],
    "currency": {
      "name": "Euro",
      "code": "EUR",
      "symbol": "€"
    },
    "tld": ".de",
    "latitude": 51.0,
    "longitude": 9.0
  },
  {
    "country": "Greece",
    "flag": "🇬🇷",
    "iso2": "GR",
    "iso3": "GRC",
    "capital": "Athens",
    "region": "Europe",
    "subregion": "Southern Europe",
    "population": 10715549,
    "area": 131990,
    "languages": ["Greek"],
    "phoneCode": "+30",
    "timezones": ["Europe/Athens"],
    "currency": {
      "name": "Euro",
      "code": "EUR",
      "symbol": "€"
    },
    "tld": ".gr",
    "latitude": 39.0,
    "longitude": 22.0
  },
  {
    "country": "India",
    "flag": "🇮🇳",
    "iso2": "IN",
    "iso3": "IND",
    "capital": "New Delhi",
    "region": "Asia",
    "subregion": "Southern Asia",
    "population": 1380004385,
    "area": 3287590,
    "languages": ["Hindi", "English"],
    "phoneCode": "+91",
    "timezones": ["Asia/Kolkata"],
    "currency": {
      "name": "Indian rupee",
      "code": "INR",
      "symbol": "₹"
    },
    "tld": ".in",
    "latitude": 20.0,
    "longitude": 77.0
  },
  {
    "country": "Indonesia",
    "flag": "🇮🇩",
    "iso2": "ID",
    "iso3": "IDN",
    "capital": "Jakarta",
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "population": 273523621,
    "area": 1904569,
    "languages": ["Indonesian"],
    "phoneCode": "+62",
    "timezones": ["Asia/Jakarta", "Asia/Pontianak", "Asia/Makassar", "Asia/Jayapura"],
    "currency": {
      "name": "Indonesian rupiah",
      "code": "IDR",
      "symbol": "Rp"
    },
    "tld": ".id",
    "latitude": -5.0,
    "longitude": 120.0
  },
  {
    "country": "Iran",
    "flag": "🇮🇷",
    "iso2": "IR",
    "iso3": "IRN",
    "capital": "Tehran",
    "region": "Asia",
    "subregion": "Southern Asia",
    "population": 83992953,
    "area": 1648195,
    "languages": ["Persian (Farsi)"],
    "phoneCode": "+98",
    "timezones": ["Asia/Tehran"],
    "currency": {
      "name": "Iranian rial",
      "code": "IRR",
      "symbol": "﷼"
    },
    "tld": ".ir",
    "latitude": 32.0,
    "longitude": 53.0
  },
  {
    "country": "Iraq",
    "flag": "🇮🇶",
    "iso2": "IQ",
    "iso3": "IRQ",
    "capital": "Baghdad",
    "region": "Asia",
    "subregion": "Western Asia",
    "population": 40222503,
    "area": 438317,
    "languages": ["Arabic", "Kurdish"],
    "phoneCode": "+964",
    "timezones": ["Asia/Baghdad"],
    "currency": {
      "name": "Iraqi dinar",
      "code": "IQD",
      "symbol": "ع.د"
    },
    "tld": ".iq",
    "latitude": 33.0,
    "longitude": 44.0
  },
  {
    "country": "Ireland",
    "flag": "🇮🇪",
    "iso2": "IE",
    "iso3": "IRL",
    "capital": "Dublin",
    "region": "Europe",
    "subregion": "Northern Europe",
    "population": 4994724,
    "area": 70273,
    "languages": ["Irish", "English"],
    "phoneCode": "+353",
    "timezones": ["Europe/Dublin"],
    "currency": {
      "name": "Euro",
      "code": "EUR",
      "symbol": "€"
    },
    "tld": ".ie",
    "latitude": 53.0,
    "longitude": -8.0
  },
  {
    "country": "Italy",
    "flag": "🇮🇹",
    "iso2": "IT",
    "iso3": "ITA",
    "capital": "Rome",
    "region": "Europe",
    "subregion": "Southern Europe",
    "population": 59554023,
    "area": 301336,
    "languages": ["Italian"],
    "phoneCode": "+39",
    "timezones": ["Europe/Rome"],
    "currency": {
      "name": "Euro",
      "code": "EUR",
      "symbol": "€"
    },
    "tld": ".it",
    "latitude": 42.83,
    "longitude": 12.83
  },
  {
    "country": "Japan",
    "flag": "🇯🇵",
    "iso2": "JP",
    "iso3": "JPN",
    "capital": "Tokyo",
    "region": "Asia",
    "subregion": "Eastern Asia",
    "population": 125836021,
    "area": 377930,
    "languages": ["Japanese"],
    "phoneCode": "+81",
    "timezones": ["Asia/Tokyo"],
    "currency": {
      "name": "Japanese yen",
      "code": "JPY",
      "symbol": "¥"
    },
    "tld": ".jp",
    "latitude": 36.0,
    "longitude": 138.0
  },
  {
    "country": "Jordan",
    "flag": "🇯🇴",
    "iso2": "JO",
    "iso3": "JOR",
    "capital": "Amman",
    "region": "Asia",
    "subregion": "Western Asia",
    "population": 10203140,
    "area": 89342,
    "languages": ["Arabic"],
    "phoneCode": "+962",
    "timezones": ["Asia/Amman"],
    "currency": {
      "name": "Jordanian dinar",
      "code": "JOD",
      "symbol": "د.ا"
    },
    "tld": ".jo",
    "latitude": 31.0,
    "longitude": 36.0
  },
  {
    "country": "Kenya",
    "flag": "🇰🇪",
    "iso2": "KE",
    "iso3": "KEN",
    "capital": "Nairobi",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "population": 53771300,
    "area": 580367,
    "languages": ["English", "Swahili"],
    "phoneCode": "+254",
    "timezones": ["Africa/Nairobi"],
    "currency": {
      "name": "Kenyan shilling",
      "code": "KES",
      "symbol": "Sh"
    },
    "tld": ".ke",
    "latitude": 1.0,
    "longitude": 38.0
  },
  {
    "country": "Kuwait",
    "flag": "🇰🇼",
    "iso2": "KW",
    "iso3": "KWT",
    "capital": "Kuwait City",
    "region": "Asia",
    "subregion": "Western Asia",
    "population": 4270563,
    "area": 17818,
    "languages": ["Arabic"],
    "phoneCode": "+965",
    "timezones": ["Asia/Kuwait"],
    "currency": {
      "name": "Kuwaiti dinar",
      "code": "KWD",
      "symbol": "د.ك"
    },
    "tld": ".kw",
    "latitude": 29.5,
    "longitude": 45.75
  },
  {
    "country": "Latvia",
    "flag": "🇱🇻",
    "iso2": "LV",
    "iso3": "LVA",
    "capital": "Riga",
    "region": "Europe",
    "subregion": "Northern Europe",
    "population": 1901548,
    "area": 64559,
    "languages": ["Latvian"],
    "phoneCode": "+371",
    "timezones": ["Europe/Riga"],
    "currency": {
      "name": "Euro",
      "code": "EUR",
      "symbol": "€"
    },
    "tld": ".lv",
    "latitude": 57.0,
    "longitude": 25.0
  },
  {
    "country": "Lebanon",
    "flag": "🇱🇧",
    "iso2": "LB",
    "iso3": "LBN",
    "capital": "Beirut",
    "region": "Asia",
    "subregion": "Western Asia",
    "population": 6825442,
    "area": 10452,
    "languages": ["Arabic", "French"],
    "phoneCode": "+961",
    "timezones": ["Asia/Beirut"],
    "currency": {
      "name": "Lebanese pound",
      "code": "LBP",
      "symbol": "ل.ل"
    },
    "tld": ".lb",
    "latitude": 33.83,
    "longitude": 35.83
  },
  {
    "country": "Liechtenstein",
    "flag": "🇱🇮",
    "iso2": "LI",
    "iso3": "LIE",
    "capital": "Vaduz",
    "region": "Europe",
    "subregion": "Western Europe",
    "population": 38137,
    "area": 160,
    "languages": ["German"],
    "phoneCode": "+423",
    "timezones": ["Europe/Vaduz"],
    "currency": {
      "name": "Swiss franc",
      "code": "CHF",
      "symbol": "Fr"
    },
    "tld": ".li",
    "latitude": 47.16,
    "longitude": 9.53
  },
  {
    "country": "Lithuania",
    "flag": "🇱🇹",
    "iso2": "LT",
    "iso3": "LTU",
    "capital": "Vilnius",
    "region": "Europe",
    "subregion": "Northern Europe",
    "population": 2794700,
    "area": 65300,
    "languages": ["Lithuanian"],
    "phoneCode": "+370",
    "timezones": ["Europe/Vilnius"],
    "currency": {
      "name": "Euro",
      "code": "EUR",
      "symbol": "€"
    },
    "tld": ".lt",
    "latitude": 56.0,
    "longitude": 24.0
  },
  {
    "country": "Luxembourg",
    "flag": "🇱🇺",
    "iso2": "LU",
    "iso3": "LUX",
    "capital": "Luxembourg",
    "region": "Europe",
    "subregion": "Western Europe",
    "population": 632275,
    "area": 2586,
    "languages": ["French", "German", "Luxembourgish"],
    "phoneCode": "+352",
    "timezones": ["Europe/Luxembourg"],
    "currency": {
      "name": "Euro",
      "code": "EUR",
      "symbol": "€"
    },
    "tld": ".lu",
    "latitude": 49.75,
    "longitude": 6.17
  },
  {
    "country": "Malaysia",
    "flag": "🇲🇾",
    "iso2": "MY",
    "iso3": "MYS",
    "capital": "Kuala Lumpur",
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "population": 32365998,
    "area": 330803,
    "languages": ["Malaysian"],
    "phoneCode": "+60",
    "timezones": ["Asia/Kuala_Lumpur"],
    "currency": {
      "name": "Malaysian ringgit",
      "code": "MYR",
      "symbol": "RM"
    },
    "tld": ".my",
    "latitude": 2.5,
    "longitude": 112.5
  },
  {
    "country": "Maldives",
    "flag": "🇲🇻",
    "iso2": "MV",
    "iso3": "MDV",
    "capital": "Malé",
    "region": "Asia",
    "subregion": "Southern Asia",
    "population": 540542,
    "area": 300,
    "languages": ["Divehi"],
    "phoneCode": "+960",
    "timezones": ["Indian/Maldives"],
    "currency": {
      "name": "Maldivian rufiyaa",
      "code": "MVR",
      "symbol": ".ރ"
    },
    "tld": ".mv",
    "latitude": 3.25,
    "longitude": 73.0
  },
  {
    "country": "Mexico",
    "flag": "🇲🇽",
    "iso2": "MX",
    "iso3": "MEX",
    "capital": "Mexico City",
    "region": "Americas",
    "subregion": "North America",
    "population": 128932753,
    "area": 1964375,
    "languages": ["Spanish"],
    "phoneCode": "+52",
    "timezones": ["America/Mexico_City"],
    "currency": {
      "name": "Mexican peso",
      "code": "MXN",
      "symbol": "$"
    },
    "tld": ".mx",
    "latitude": 23.0,
    "longitude": -102.0
  },
  {
    "country": "Monaco",
    "flag": "🇲🇨",
    "iso2": "MC",
    "iso3": "MCO",
    "capital": "Monaco",
    "region": "Europe",
    "subregion": "Western Europe",
    "population": 39244,
    "area": 2,
    "languages": ["French"],
    "phoneCode": "+377",
    "timezones": ["Europe/Monaco"],
    "currency": {
      "name": "Euro",
      "code": "EUR",
      "symbol": "€"
    },
    "tld": ".mc",
    "latitude": 43.73,
    "longitude": 7.42
  },
  {
    "country": "Morocco",
    "flag": "🇲🇦",
    "iso2": "MA",
    "iso3": "MAR",
    "capital": "Rabat",
    "region": "Africa",
    "subregion": "Northern Africa",
    "population": 36910558,
    "area": 446550,
    "languages": ["Arabic"],
    "phoneCode": "+212",
    "timezones": ["Africa/Casablanca"],
    "currency": {
      "name": "Moroccan dirham",
      "code": "MAD",
      "symbol": "د.م."
    },
    "tld": ".ma",
    "latitude": 32.0,
    "longitude": -5.0
  },
  {
    "country": "Nepal",
    "flag": "🇳🇵",
    "iso2": "NP",
    "iso3": "NPL",
    "capital": "Kathmandu",
    "region": "Asia",
    "subregion": "Southern Asia",
    "population": 29136808,
    "area": 147181,
    "languages": ["Nepali"],
    "phoneCode": "+977",
    "timezones": ["Asia/Kathmandu"],
    "currency": {
      "name": "Nepalese rupee",
      "code": "NPR",
      "symbol": "₨"
    },
    "tld": ".np",
    "latitude": 28.0,
    "longitude": 84.0
  },
  {
    "country": "Netherlands",
    "flag": "🇳🇱",
    "iso2": "NL",
    "iso3": "NLD",
    "capital": "Amsterdam",
    "region": "Europe",
    "subregion": "Western Europe",
    "population": 17441139,
    "area": 41850,
    "languages": ["Dutch"],
    "phoneCode": "+31",
    "timezones": ["Europe/Amsterdam"],
    "currency": {
      "name": "Euro",
      "code": "EUR",
      "symbol": "€"
    },
    "tld": ".nl",
    "latitude": 52.5,
    "longitude": 5.75
  },
  {
    "country": "New Zealand",
    "flag": "🇳🇿",
    "iso2": "NZ",
    "iso3": "NZL",
    "capital": "Wellington",
    "region": "Oceania",
    "subregion": "Australia and New Zealand",
    "population": 5084300,
    "area": 270467,
    "languages": ["English", "Māori"],
    "phoneCode": "+64",
    "timezones": ["Pacific/Auckland"],
    "currency": {
      "name": "New Zealand dollar",
      "code": "NZD",
      "symbol": "$"
    },
    "tld": ".nz",
    "latitude": -41.0,
    "longitude": 174.0
  },
  {
    "country": "Nigeria",
    "flag": "🇳🇬",
    "iso2": "NG",
    "iso3": "NGA",
    "capital": "Abuja",
    "region": "Africa",
    "subregion": "Western Africa",
    "population": 206139587,
    "area": 923768,
    "languages": ["English"],
    "phoneCode": "+234",
    "timezones": ["Africa/Lagos"],
    "currency": {
      "name": "Nigerian naira",
      "code": "NGN",
      "symbol": "₦"
    },
    "tld": ".ng",
    "latitude": 10.0,
    "longitude": 8.0
  },
  {
    "country": "Norway",
    "flag": "🇳🇴",
    "iso2": "NO",
    "iso3": "NOR",
    "capital": "Oslo",
    "region": "Europe",
    "subregion": "Northern Europe",
    "population": 5379475,
    "area": 323802,
    "languages": ["Norwegian"],
    "phoneCode": "+47",
    "timezones": ["Europe/Oslo"],
    "currency": {
      "name": "Norwegian krone",
      "code": "NOK",
      "symbol": "kr"
    },
    "tld": ".no",
    "latitude": 62.0,
    "longitude": 10.0
  },
  {
    "country": "Oman",
    "flag": "🇴🇲",
    "iso2": "OM",
    "iso3": "OMN",
    "capital": "Muscat",
    "region": "Asia",
    "subregion": "Western Asia",
    "population": 5106622,
    "area": 309500,
    "languages": ["Arabic"],
    "phoneCode": "+968",
    "timezones": ["Asia/Muscat"],
    "currency": {
      "name": "Omani rial",
      "code": "OMR",
      "symbol": "ر.ع."
    },
    "tld": ".om",
    "latitude": 21.0,
    "longitude": 57.0
  },
  {
    "country": "Pakistan",
    "flag": "🇵🇰",
    "iso2": "PK",
    "iso3": "PAK",
    "capital": "Islamabad",
    "region": "Asia",
    "subregion": "Southern Asia",
    "population": 220892331,
    "area": 881912,
    "languages": ["Urdu", "English"],
    "phoneCode": "+92",
    "timezones": ["Asia/Karachi"],
    "currency": {
      "name": "Pakistani rupee",
      "code": "PKR",
      "symbol": "₨"
    },
    "tld": ".pk",
    "latitude": 30.0,
    "longitude": 70.0
  },
  {
    "country": "Philippines",
    "flag": "🇵🇭",
    "iso2": "PH",
    "iso3": "PHL",
    "capital": "Manila",
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "population": 109581085,
    "area": 342353,
    "languages": ["Filipino", "English"],
    "phoneCode": "+63",
    "timezones": ["Asia/Manila"],
    "currency": {
      "name": "Philippine peso",
      "code": "PHP",
      "symbol": "₱"
    },
    "tld": ".ph",
    "latitude": 13.0,
    "longitude": 122.0
  },
  {
    "country": "Poland",
    "flag": "🇵🇱",
    "iso2": "PL",
    "iso3": "POL",
    "capital": "Warsaw",
    "region": "Europe",
    "subregion": "Eastern Europe",
    "population": 37950802,
    "area": 312696,
    "languages": ["Polish"],
    "phoneCode": "+48",
    "timezones": ["Europe/Warsaw"],
    "currency": {
      "name": "Polish złoty",
      "code": "PLN",
      "symbol": "zł"
    },
    "tld": ".pl",
    "latitude": 52.0,
    "longitude": 20.0
  },
  {
    "country": "Portugal",
    "flag": "🇵🇹",
    "iso2": "PT",
    "iso3": "PRT",
    "capital": "Lisbon",
    "region": "Europe",
    "subregion": "Southern Europe",
    "population": 10305564,
    "area": 92090,
    "languages": ["Portuguese"],
    "phoneCode": "+351",
    "timezones": ["Europe/Lisbon"],
    "currency": {
      "name": "Euro",
      "code": "EUR",
      "symbol": "€"
    },
    "tld": ".pt",
    "latitude": 39.5,
    "longitude": -8.0
  },
  {
    "country": "Qatar",
    "flag": "🇶🇦",
    "iso2": "QA",
    "iso3": "QAT",
    "capital": "Doha",
    "region": "Asia",
    "subregion": "Western Asia",
    "population": 2881060,
    "area": 11586,
    "languages": ["Arabic"],
    "phoneCode": "+974",
    "timezones": ["Asia/Qatar"],
    "currency": {
      "name": "Qatari riyal",
      "code": "QAR",
      "symbol": "ر.ق"
    },
    "tld": ".qa",
    "latitude": 25.5,
    "longitude": 51.25
  },
  {
    "country": "Romania",
    "flag": "🇷🇴",
    "iso2": "RO",
    "iso3": "ROU",
    "capital": "Bucharest",
    "region": "Europe",
    "subregion": "Eastern Europe",
    "population": 19286123,
    "area": 238391,
    "languages": ["Romanian"],
    "phoneCode": "+40",
    "timezones": ["Europe/Bucharest"],
    "currency": {
      "name": "Romanian leu",
      "code": "RON",
      "symbol": "lei"
    },
    "tld": ".ro",
    "latitude": 46.0,
    "longitude": 25.0
  },
  {
    "country": "Russia",
    "flag": "🇷🇺",
    "iso2": "RU",
    "iso3": "RUS",
    "capital": "Moscow",
    "region": "Europe",
    "subregion": "Eastern Europe",
    "population": 144104080,
    "area": 17098242,
    "languages": ["Russian"],
    "phoneCode": "+7",
    "timezones": ["Europe/Moscow"],
    "currency": {
      "name": "Russian ruble",
      "code": "RUB",
      "symbol": "₽"
    },
    "tld": ".ru",
    "latitude": 60.0,
    "longitude": 100.0
  },
  {
    "country": "Saudi Arabia",
    "flag": "🇸🇦",
    "iso2": "SA",
    "iso3": "SAU",
    "capital": "Riyadh",
    "region": "Asia",
    "subregion": "Western Asia",
    "population": 34813867,
    "area": 2149690,
    "languages": ["Arabic"],
    "phoneCode": "+966",
    "timezones": ["Asia/Riyadh"],
    "currency": {
      "name": "Saudi riyal",
      "code": "SAR",
      "symbol": "ر.س"
    },
    "tld": ".sa",
    "latitude": 25.0,
    "longitude": 45.0
  },
  {
    "country": "Singapore",
    "flag": "🇸🇬",
    "iso2": "SG",
    "iso3": "SGP",
    "capital": "Singapore",
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "population": 5685807,
    "area": 710,
    "languages": ["English", "Malay", "Mandarin", "Tamil"],
    "phoneCode": "+65",
    "timezones": ["Asia/Singapore"],
    "currency": {
      "name": "Singapore dollar",
      "code": "SGD",
      "symbol": "$"
    },
    "tld": ".sg",
    "latitude": 1.37,
    "longitude": 103.8
  },
  {
    "country": "South Africa",
    "flag": "🇿🇦",
    "iso2": "ZA",
    "iso3": "ZAF",
    "capital": "Pretoria",
    "region": "Africa",
    "subregion": "Southern Africa",
    "population": 59308690,
    "area": 1221037,
    "languages": ["Afrikaans", "English", "Zulu"],
    "phoneCode": "+27",
    "timezones": ["Africa/Johannesburg"],
    "currency": {
      "name": "South African rand",
      "code": "ZAR",
      "symbol": "R"
    },
    "tld": ".za",
    "latitude": -29.0,
    "longitude": 24.0
  },
  {
    "country": "South Korea",
    "flag": "🇰🇷",
    "iso2": "KR",
    "iso3": "KOR",
    "capital": "Seoul",
    "region": "Asia",
    "subregion": "Eastern Asia",
    "population": 51780579,
    "area": 100210,
    "languages": ["Korean"],
    "phoneCode": "+82",
    "timezones": ["Asia/Seoul"],
    "currency": {
      "name": "South Korean won",
      "code": "KRW",
      "symbol": "₩"
    },
    "tld": ".kr",
    "latitude": 37.0,
    "longitude": 127.5
  },
  {
    "country": "Spain",
    "flag": "🇪🇸",
    "iso2": "ES",
    "iso3": "ESP",
    "capital": "Madrid",
    "region": "Europe",
    "subregion": "Southern Europe",
    "population": 47351567,
    "area": 505992,
    "languages": ["Spanish"],
    "phoneCode": "+34",
    "timezones": ["Europe/Madrid"],
    "currency": {
      "name": "Euro",
      "code": "EUR",
      "symbol": "€"
    },
    "tld": ".es",
    "latitude": 40.0,
    "longitude": -4.0
  },
  {
    "country": "Sri Lanka",
    "flag": "🇱🇰",
    "iso2": "LK",
    "iso3": "LKA",
    "capital": "Colombo",
    "region": "Asia",
    "subregion": "Southern Asia",
    "population": 21919000,
    "area": 65610,
    "languages": ["Sinhala", "Tamil"],
    "phoneCode": "+94",
    "timezones": ["Asia/Colombo"],
    "currency": {
      "name": "Sri Lankan rupee",
      "code": "LKR",
      "symbol": "Rs"
    },
    "tld": ".lk",
    "latitude": 7.0,
    "longitude": 81.0
  },
  {
    "country": "Sweden",
    "flag": "🇸🇪",
    "iso2": "SE",
    "iso3": "SWE",
    "capital": "Stockholm",
    "region": "Europe",
    "subregion": "Northern Europe",
    "population": 10353442,
    "area": 450295,
    "languages": ["Swedish"],
    "phoneCode": "+46",
    "timezones": ["Europe/Stockholm"],
    "currency": {
      "name": "Swedish krona",
      "code": "SEK",
      "symbol": "kr"
    },
    "tld": ".se",
    "latitude": 62.0,
    "longitude": 15.0
  },
  {
    "country": "Switzerland",
    "flag": "🇨🇭",
    "iso2": "CH",
    "iso3": "CHE",
    "capital": "Bern",
    "region": "Europe",
    "subregion": "Western Europe",
    "population": 8636896,
    "area": 41284,
    "languages": ["German", "French", "Italian"],
    "phoneCode": "+41",
    "timezones": ["Europe/Zurich"],
    "currency": {
      "name": "Swiss franc",
      "code": "CHF",
      "symbol": "Fr"
    },
    "tld": ".ch",
    "latitude": 47.0,
    "longitude": 8.0
  },
  {
    "country": "Taiwan",
    "flag": "🇹🇼",
    "iso2": "TW",
    "iso3": "TWN",
    "capital": "Taipei",
    "region": "Asia",
    "subregion": "Eastern Asia",
    "population": 23568378,
    "area": 36193,
    "languages": ["Chinese"],
    "phoneCode": "+886",
    "timezones": ["Asia/Taipei"],
    "currency": {
      "name": "New Taiwan dollar",
      "code": "TWD",
      "symbol": "$"
    },
    "tld": ".tw",
    "latitude": 23.5,
    "longitude": 121.0
  },
  {
    "country": "Thailand",
    "flag": "🇹🇭",
    "iso2": "TH",
    "iso3": "THA",
    "capital": "Bangkok",
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "population": 69799978,
    "area": 513120,
    "languages": ["Thai"],
    "phoneCode": "+66",
    "timezones": ["Asia/Bangkok"],
    "currency": {
      "name": "Thai baht",
      "code": "THB",
      "symbol": "฿"
    },
    "tld": ".th",
    "latitude": 15.0,
    "longitude": 100.0
  },
  {
    "country": "Turkey",
    "flag": "🇹🇷",
    "iso2": "TR",
    "iso3": "TUR",
    "capital": "Ankara",
    "region": "Asia",
    "subregion": "Western Asia",
    "population": 84339067,
    "area": 783562,
    "languages": ["Turkish"],
    "phoneCode": "+90",
    "timezones": ["Europe/Istanbul"],
    "currency": {
      "name": "Turkish lira",
      "code": "TRY",
      "symbol": "₺"
    },
    "tld": ".tr",
    "latitude": 39.0,
    "longitude": 35.0
  },
  {
    "country": "Ukraine",
    "flag": "🇺🇦",
    "iso2": "UA",
    "iso3": "UKR",
    "capital": "Kyiv",
    "region": "Europe",
    "subregion": "Eastern Europe",
    "population": 44134693,
    "area": 603500,
    "languages": ["Ukrainian"],
    "phoneCode": "+380",
    "timezones": ["Europe/Kiev"],
    "currency": {
      "name": "Ukrainian hryvnia",
      "code": "UAH",
      "symbol": "₴"
    },
    "tld": ".ua",
    "latitude": 49.0,
    "longitude": 32.0
  },
  {
    "country": "United Arab Emirates",
    "flag": "🇦🇪",
    "iso2": "AE",
    "iso3": "ARE",
    "capital": "Abu Dhabi",
    "region": "Asia",
    "subregion": "Western Asia",
    "population": 9890400,
    "area": 83600,
    "languages": ["Arabic"],
    "phoneCode": "+971",
    "timezones": ["Asia/Dubai"],
    "currency": {
      "name": "United Arab Emirates dirham",
      "code": "AED",
      "symbol": "د.إ"
    },
    "tld": ".ae",
    "latitude": 24.0,
    "longitude": 54.0
  },
  {
    "country": "United Kingdom",
    "flag": "🇬🇧",
    "iso2": "GB",
    "iso3": "GBR",
    "capital": "London",
    "region": "Europe",
    "subregion": "Northern Europe",
    "population": 67215293,
    "area": 242900,
    "languages": ["English"],
    "phoneCode": "+44",
    "timezones": ["Europe/London"],
    "currency": {
      "name": "Pound sterling",
      "code": "GBP",
      "symbol": "£"
    },
    "tld": ".uk",
    "latitude": 54.0,
    "longitude": -2.0
  },
  {
    "country": "United States of America",
    "flag": "🇺🇸",
    "iso2": "US",
    "iso3": "USA",
    "capital": "Washington, D.C.",
    "region": "Americas",
    "subregion": "Northern America",
    "population": 329484123,
    "area": 9372610,
    "languages": ["English"],
    "phoneCode": "+1",
    "timezones": ["America/New_York"],
    "currency": {
      "name": "United States dollar",
      "code": "USD",
      "symbol": "$"
    },
    "tld": ".us",
    "latitude": 38.0,
    "longitude": -97.0
  },
  {
    "country": "Vietnam",
    "flag": "🇻🇳",
    "iso2": "VN",
    "iso3": "VNM",
    "capital": "Hanoi",
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "population": 97338583,
    "area": 331212,
    "languages": ["Vietnamese"],
    "phoneCode": "+84",
    "timezones": ["Asia/Ho_Chi_Minh"],
    "currency": {
      "name": "Vietnamese đồng",
      "code": "VND",
      "symbol": "₫"
    },
    "tld": ".vn",
    "latitude": 16.17,
    "longitude": 107.83
  },
  {
    "country": "Yemen",
    "flag": "🇾🇪",
    "iso2": "YE",
    "iso3": "YEM",
    "capital": "Sana'a",
    "region": "Asia",
    "subregion": "Western Asia",
    "population": 29825968,
    "area": 527968,
    "languages": ["Arabic"],
    "phoneCode": "+967",
    "timezones": ["Asia/Aden"],
    "currency": {
      "name": "Yemeni rial",
      "code": "YER",
      "symbol": "﷼"
    },
    "tld": ".ye",
    "latitude": 15.0,
    "longitude": 48.0
  },
  {
    "country": "Zambia",
    "flag": "🇿🇲",
    "iso2": "ZM",
    "iso3": "ZMB",
    "capital": "Lusaka",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "population": 18383955,
    "area": 752612,
    "languages": ["English"],
    "phoneCode": "+260",
    "timezones": ["Africa/Lusaka"],
    "currency": {
      "name": "Zambian kwacha",
      "code": "ZMW",
      "symbol": "ZK"
    },
    "tld": ".zm",
    "latitude": -15.0,
    "longitude": 30.0
  },
  {
    "country": "Zimbabwe",
    "flag": "🇿🇼",
    "iso2": "ZW",
    "iso3": "ZWE",
    "capital": "Harare",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "population": 14862927,
    "area": 390757,
    "languages": ["English", "Shona", "Ndebele"],
    "phoneCode": "+263",
    "timezones": ["Africa/Harare"],
    "currency": {
      "name": "Zimbabwean dollar",
      "code": "ZWL",
      "symbol": "$"
    },
    "tld": ".zw",
    "latitude": -20.0,
    "longitude": 30.0
  }
];

