export const stateCodeMapping = [
    { id: "36", state: "Andaman and Nicobar Islands", stateCode: "AN" },
    { id: "35", state: "Andhra Pradesh", stateCode: "AP" },
    { id: "34", state: "Arunachal Pradesh", stateCode: "AR" },
    { id: "33", state: "Assam", stateCode: "AS" },
    { id: "32", state: "Bihar", stateCode: "BR" },
    { id: "31", state: "Chandigarh", stateCode: "CH" },
    { id: "30", state: "Chhattisgarh", stateCode: "CG" },
    { id: "29", state: "Dadra and Nagar Haveli", stateCode: "DN" },
    { id: "28", state: "Daman and Diu", stateCode: "DD" },
    { id: "27", state: "Delhi", stateCode: "DL" },
    { id: "26", state: "Goa", stateCode: "GA" },
    { id: "25", state: "Gujarat", stateCode: "GJ" },
    { id: "24", state: "Haryana", stateCode: "HR" },
    { id: "23", state: "Himachal Pradesh", stateCode: "HP" },
    { id: "22", state: "Jammu and Kashmir", stateCode: "JK" },
    { id: "21", state: "Jharkhand", stateCode: "JH" },
    { id: "20", state: "Karnataka", stateCode: "KA" },
    { id: "37", state: "Kerala", stateCode: "KL" },
    { id: "19", state: "Ladakh", stateCode: "LA" },
    { id: "18", state: "Lakshadweep", stateCode: "LD" },
    { id: "17", state: "Madhya Pradesh", stateCode: "MP" },
    { id: "16", state: "Maharashtra", stateCode: "MH" },
    { id: "15", state: "Manipur", stateCode: "MN" },
    { id: "14", state: "Meghalaya", stateCode: "ML" },
    { id: "13", state: "Mizoram", stateCode: "MZ" },
    { id: "12", state: "Nagaland", stateCode: "NL" },
    { id: "11", state: "Odisha", stateCode: "OD" },
    { id: "10", state: "Puducherry", stateCode: "PY" },
    { id: "9", state: "Punjab", stateCode: "PB" },
    { id: "8", state: "Rajasthan", stateCode: "RJ" },
    { id: "7", state: "Sikkim", stateCode: "SK" },
    { id: "6", state: "Tamil Nadu", stateCode: "TN" },
    { id: "5", state: "Telangana", stateCode: "TS" },
    { id: "4", state: "Tripura", stateCode: "TR" },
    { id: "3", state: "Uttar Pradesh", stateCode: "UP" },
    { id: "2", state: "Uttarakhand", stateCode: "UK" },
    { id: "1", state: "West Bengal", stateCode: "WB" }
];