// data/staticLeadsData.js - Static Data (Replace with API calls)
export const STATIC_LEADS_DATA = [
  {
    id: 1,
    name: 'John Anderson',
    phone: '+1-555-0101',
    email: 'john.anderson@company.com',
    company: 'Tech Solutions Inc',
    status: 'interested',
    priority: 'high',
    lastContact: '2024-10-28',
    nextFollowUp: '2024-11-02',
    leadValue: 5000,
    source: 'LinkedIn',
    assignedDate: '2024-10-15',
    notes: 'Very interested in our enterprise package. Mentioned budget approval needed by end of month.',
  },
  {
    id: 2,
    name: 'Sarah Mitchell',
    phone: '+1-555-0102',
    email: 'sarah.m@business.com',
    company: 'Global Enterprises',
    status: 'contacted',
    priority: 'medium',
    lastContact: '2024-10-27',
    nextFollowUp: '2024-11-03',
    leadValue: 3500,
    source: 'Referral',
    assignedDate: '2024-10-20',
    notes: 'Initial call completed. Waiting for their team feedback.',
  },
  {
    id: 3,
    name: 'Michael Chen',
    phone: '+1-555-0103',
    email: 'mchen@startup.io',
    company: 'Innovation Labs',
    status: 'new',
    priority: 'high',
    lastContact: '2024-10-29',
    nextFollowUp: '2024-11-01',
    leadValue: 8000,
    source: 'Cold Call',
    assignedDate: '2024-10-29',
    notes: 'New lead from cold calling campaign. Showed immediate interest.',
  },
  {
    id: 4,
    name: 'Emily Rodriguez',
    phone: '+1-555-0104',
    email: 'emily.r@corp.com',
    company: 'Corporate Solutions',
    status: 'follow-up',
    priority: 'medium',
    lastContact: '2024-10-25',
    nextFollowUp: '2024-11-05',
    leadValue: 4200,
    source: 'Email Campaign',
    assignedDate: '2024-10-18',
    notes: 'Needs follow-up on pricing details. Decision maker is on vacation until Nov 1st.',
  },
  {
    id: 5,
    name: 'David Thompson',
    phone: '+1-555-0105',
    email: 'dthompson@business.net',
    company: 'Premier Group',
    status: 'not-interested',
    priority: 'low',
    lastContact: '2024-10-26',
    nextFollowUp: '2024-12-01',
    leadValue: 2000,
    source: 'Trade Show',
    assignedDate: '2024-10-22',
    notes: 'Not interested at this time. Budget constraints. Revisit in Q1 2025.',
  },
  {
    id: 6,
    name: 'Jessica Lee',
    phone: '+1-555-0106',
    email: 'jlee@company.org',
    company: 'Digital Ventures',
    status: 'interested',
    priority: 'high',
    lastContact: '2024-10-28',
    nextFollowUp: '2024-11-04',
    leadValue: 6500,
    source: 'LinkedIn',
    assignedDate: '2024-10-16',
    notes: 'Highly interested. Requested demo for next week. Potential for upsell.',
  },
  {
    id: 7,
    name: 'Robert Martinez',
    phone: '+1-555-0107',
    email: 'rmartinez@enterprise.com',
    company: 'Enterprise Corp',
    status: 'contacted',
    priority: 'high',
    lastContact: '2024-10-29',
    nextFollowUp: '2024-11-02',
    leadValue: 7200,
    source: 'Referral',
    assignedDate: '2024-10-24',
    notes: 'Initial contact successful. Scheduling meeting with procurement team.',
  },
  {
    id: 8,
    name: 'Amanda White',
    phone: '+1-555-0108',
    email: 'awhite@business.co',
    company: 'White Industries',
    status: 'new',
    priority: 'medium',
    lastContact: '2024-10-29',
    nextFollowUp: '2024-11-06',
    leadValue: 3800,
    source: 'Cold Call',
    assignedDate: '2024-10-29',
    notes: 'New prospect. Interested in learning more about our services.',
  },
  {
    id: 9,
    name: 'Christopher Brown',
    phone: '+1-555-0109',
    email: 'cbrown@tech.com',
    company: 'Tech Innovations',
    status: 'follow-up',
    priority: 'medium',
    lastContact: '2024-10-27',
    nextFollowUp: '2024-11-08',
    leadValue: 4900,
    source: 'Email Campaign',
    assignedDate: '2024-10-19',
    notes: 'Waiting for technical specifications. Will follow up after review.',
  },
  {
    id: 10,
    name: 'Lisa Johnson',
    phone: '+1-555-0110',
    email: 'ljohnson@company.com',
    company: 'Johnson & Associates',
    status: 'interested',
    priority: 'low',
    lastContact: '2024-10-28',
    nextFollowUp: '2024-11-10',
    leadValue: 2500,
    source: 'Referral',
    assignedDate: '2024-10-21',
    notes: 'Interested but lower priority. Budget constraints. Good for future opportunity.',
  },
    {
    id: 6,
    name: 'Jessica Lee',
    phone: '+1-555-0106',
    email: 'jlee@company.org',
    company: 'Digital Ventures',
    status: 'interested',
    priority: 'high',
    lastContact: '2024-10-28',
    nextFollowUp: '2024-11-04',
    leadValue: 6500,
    source: 'LinkedIn',
    assignedDate: '2024-10-16',
    notes: 'Highly interested. Requested demo for next week. Potential for upsell.',
  },
  {
    id: 7,
    name: 'Robert Martinez',
    phone: '+1-555-0107',
    email: 'rmartinez@enterprise.com',
    company: 'Enterprise Corp',
    status: 'contacted',
    priority: 'high',
    lastContact: '2024-10-29',
    nextFollowUp: '2024-11-02',
    leadValue: 7200,
    source: 'Referral',
    assignedDate: '2024-10-24',
    notes: 'Initial contact successful. Scheduling meeting with procurement team.',
  },
];